#!/usr/bin/env ruby

require 'post_images_bot/configuration'

config = PostImagesBot::Configuration.new

config.parse_command_line(ARGV)

config.read_configuration

puts config.last_post
config.last_post = Time.now.to_i
puts config.last_post
puts config.configuration.to_yaml
