#!/usr/bin/env ruby

require 'post_images_bot'

config = PostImagesBot::Configuration.new

config.parse_command_line(ARGV)

config.read_configuration

bot = PostImagesBot::PostImagesBot.new(config)

config = bot.run

config.write_configuration
